# Support the author by using the funding link below.
# Maintained by Hieu Trung Nguyen with the help of awsome contributors.
# GitHub Sponsors: https://github.com/sponsors/HieuTNg
# Buy Me a Coffee: https://buymeacoffee.com/hieutng
# Kofi: https://ko-fi.com/hieutng

github: hieutng
buy-me-a-coffee: hieutng
ko-fi: hieutng